
server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

#spring:
#  datasource:
#    url: jdbc:mysql://172.16.2.154:3307/aqs_test
#    driver-class-name: com.mysql.jdbc.Driver
#    username: aqs
#    password: r5rD6a8NBnWP9NGs
